# Generated by Django 5.2.6 on 2025-09-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursos',
            name='id',
        ),
        migrations.AddField(
            model_name='recursos',
            name='descripcion_recurso',
            field=models.CharField(max_length=150, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='recursos',
            name='estado_recurso',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible para reserva'), ('USO', 'En uso'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DISPONIBLE', max_length=13),
        ),
        migrations.AddField(
            model_name='recursos',
            name='id_recurso',
            field=models.CharField(default='TEMP', max_length=15, primary_key=True, serialize=False, verbose_name='ID o Código de Recurso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recursos',
            name='tipo_recurso',
            field=models.CharField(choices=[('SALA', 'Sala de Reuniones'), ('PC', 'Computador Portátil'), ('PYT', 'Proyector'), ('TV', 'Televisor'), ('MON', 'Monitor para PC'), ('HRRM', 'Herramienta')], default='TEMP', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recursos',
            name='ubicacion_recurso',
            field=models.CharField(choices=[('SUR', 'Bloque Sur'), ('NORTE', 'Bloque Norte'), ('CENTRO', 'Bloque Centro')], default='TEMP', max_length=6),
            preserve_default=False,
        ),
    ]
