# Generated by Django 5.2.6 on 2025-11-14 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_remove_recursos_id_recursos_descripcion_recurso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursos',
            name='id_recurso',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID o Código de Recurso'),
        ),
    ]
