# Generated by Django 5.2.7 on 2025-10-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Cliente Final'), ('STAFF', 'Personal de Servicio'), ('MANAGER', 'Gerente'), ('ADMIN', 'Administrador')], default='CLIENT', max_length=10),
        ),
    ]
