# Generated by Django 5.1.7 on 2025-11-11 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning')], max_length=20)),
                ('level', models.CharField(choices=[('usuarios', 'Usuarios'), ('roles', 'Roles'), ('recursos', 'Recursos'), ('reservas', 'Reservas'), ('sistema', 'Sistema'), ('otro', 'Otro')], max_length=20)),
                ('message', models.TextField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
