# Generated by Django 5.2.6 on 2025-11-14 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={},
        ),
    ]
