# Generated by Django 5.2.6 on 2025-09-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roles',
            name='id',
        ),
        migrations.AddField(
            model_name='roles',
            name='descripcion_rol',
            field=models.CharField(max_length=150, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='roles',
            name='id_rol',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
