# Generated by Django 5.2.6 on 2025-09-13 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recursos', '0002_remove_recursos_id_recursos_descripcion_recurso_and_more'),
        ('usuarios', '0002_alter_usuarios_contrasena'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('estado_reserva', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=10, verbose_name='Estado de la reserva')),
                ('fecha_inicio', models.DateTimeField(null=True, verbose_name='Fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(null=True, verbose_name='Fecha y hora de fin')),
                ('id_recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='recursos.recursos')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='usuarios.usuarios')),
            ],
        ),
    ]
