# Generated by Django 5.2.6 on 2025-10-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('estado_reserva', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=10, verbose_name='Estado de la reserva')),
                ('fecha_inicio', models.DateTimeField(null=True, verbose_name='Fecha y hora de inicio')),
                ('fecha_fin', models.DateTimeField(null=True, verbose_name='Fecha y hora de fin')),
            ],
        ),
    ]
