# Generated by Django 5.2.6 on 2025-10-23 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='id',
            new_name='id_user',
        ),
    ]
