# Generated by Django 5.2.6 on 2025-09-12 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='productos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ventas.productos'),
        ),
    ]
