# Generated by Django 5.2.7 on 2025-10-18 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_duration_hours_servicetype_cost_per_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_start_time', models.TimeField(default='09:00:00', verbose_name='Hora de Apertura')),
                ('operating_end_time', models.TimeField(default='18:00:00', verbose_name='Hora de Cierre')),
                ('slot_duration_minutes', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(30)], verbose_name='Duración del Slot (minutos)')),
            ],
            options={
                'verbose_name': 'Configuración Global de Reserva',
                'verbose_name_plural': 'Configuración Global de Reservas',
            },
        ),
    ]
