# Generated by Django 5.2.6 on 2025-09-12 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0002_remove_roles_id_roles_descripcion_rol_roles_id_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Cedula del Usuario')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre del usuario')),
                ('email_usuario', models.CharField(max_length=50, verbose_name='Email del usuario')),
                ('contrasena', models.CharField(max_length=15, verbose_name='Email del usuario')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='roles.roles')),
            ],
        ),
    ]
