# Generated by Django 5.2.6 on 2025-10-23 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='id_rol',
            new_name='rol',
        ),
    ]
