# Generated by Django 5.2.6 on 2025-09-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=15, verbose_name='Contraseña del usuario'),
        ),
    ]
