# Generated by Django 5.2.6 on 2025-11-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_id_rol_usuarios_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email_usuario',
            field=models.CharField(max_length=50, unique=False, verbose_name='Email del usuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre_usuario',
            field=models.CharField(max_length=50, unique=False, verbose_name='Nombre del usuario'),
        ),
    ]
