# Generated by Django 5.2.6 on 2025-11-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_email_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='email_usuario',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre_usuario',
        ),
    ]
